# Add/remove 'critical' label if issue contains the words 'urgent' or 'critical'
critical:
  - "(critical|urgent)"

cli:
  - "/(cli|command)/i"

daemon:
  - "daemon"

coordinator:
  - "coordinator"

runtime:
  - "runtime"

python:
  - "python"

c:
  - "/\bc\b/i"

c++:
  - "cxx"

rust:
  - "rust"

windows:
  - "windows"

macos:
  - "macos"

linux:
  - "(linux|ubuntu)"

bug:
  - "bug"

documentation:
  - "(doc|documentation)"
